<section class="cf">
    <div id="slides">
            <img src="<?php echo $this->getSkinUrl('images/pic6.jpg') ?>" width="457" height="327" alt="pic6"> 
            <img src="<?php echo $this->getSkinUrl('images/pic7.jpg') ?>" width="457" height="327" alt="pic7"> 
            <img src="<?php echo $this->getSkinUrl('images/pic10.jpg') ?>" width="457" height="327" alt="pic10"> 
            <img src="<?php echo $this->getSkinUrl('images/pic1.jpg') ?>" width="457" height="327" alt="pic1"> 
            <img src="<?php echo $this->getSkinUrl('images/pic2.jpg') ?>" width="457" height="327" alt="pic2"> 
            <img src="<?php echo $this->getSkinUrl('images/pic12.jpg') ?>" width="457" height="327" alt="pic12"> 
            <img src="<?php echo $this->getSkinUrl('images/pic4.jpg') ?>" width="457" height="327" alt="pic4"> 
            <img src="<?php echo $this->getSkinUrl('images/pic9.jpg') ?>" width="457" height="327" alt="pic9"> 
            <img src="<?php echo $this->getSkinUrl('images/pic5.jpg') ?>" width="457" height="327" alt="pic5">
    </div> <!-- end slides -->

    <div class="create">
        <div>
            <a href="http://www.foreverframe.com/products/forever-frame/forever-frame.html">Create Your Frame</a>
        </div>
        <h1>The Forever Frame</h1>
        <h2>The NEWEST in Wedding Unity Sand Ceremony vessels!</h2>
        <p>Our patented design PREVENTS SAND FROM MIXING. Don't let your sand mix up in a vase or knock off shadow box.</p>
        <ul>
            <li>Keeper Plate&trade; included to HOLD SAND IN PLACE during transport</li>
            <li>Sealed sand chamber prevents leaks</li>
            <li>Exchange photo ANY TIME without disturbing the sand design</li>
            <li>Perfect for Beach Unity Ceremonies</li>
            <li>Create wedding vows around the unity ceremony to make it even more special</li>
        </ul>
        <p><a href="http://www.favourlicious.ca" target="_blank">CANADIAN CUSTOMERS</a> SAVE SHIPPING AND CUSTOMS CHARGES!</p>
    </div> <!-- end create -->
</section>

<section id="packageDeals" class="cf">
    <h1>Keepsake Ideas</h1>
    <div class="package">
        <!-- <a href="personalized-wedding-frame.php"> -->
            <img src="<?php echo $this->getSkinUrl('images/banner_wedding.jpg') ?>" width="176" height="123" border="0" alt="Unity Sand Ceremonies">
            <div class="blue">
                <h2>Unity Sand Ceremonies</h2>
                <p>Couples who choose to include a Unity Sand Ceremony in their wedding can create a lasting memory that melds the symbolism of the ceremony with a physical reminder of their special day...forever.</p>
            </div>
        <!-- </a> -->
    </div>
    <div class="package">
        <!-- <a href="shadow-box-frames.php"> -->
                <img src="<?php echo $this->getSkinUrl('images/banner_shadowbox.jpg') ?>" width="176" height="123" border="0" alt="Shadow Box Frame" />
            <div class="blue">
                <h2>Shadow Box</h2>
                <p>The most unique shadow box available. Add a photo or just engraving. Add colored sand, glass, beads, shells, whatever your imagination can see.</p>
            </div>
        <!-- </a> -->
    </div>
    <div class="package">
        <!-- <a href="graduation-picture-frame.php"> -->
            <img src="<?php echo $this->getSkinUrl('images/banner_graduation.jpg') ?>" width="176" height="123" border="0" alt="Graduations" />
            <div class="blue">
                <h2>Graduations</h2>
                <p>Graduates love to add sand in their school colors and join the photo with the tassel from that important day.</p>
            </div>
        <!-- </a> -->
    </div>
    <div class="package">
        <!-- <a href="family-sand-ceremony.php"> -->
            <img src="<?php echo $this->getSkinUrl('images/banner_birthday.jpg') ?>" width="176" height="123" border="0" alt="Birthday / Baby Shower" />
            <div class="blue">
                <h2>Birthday/Baby Shower</h2>
                <p>The most unique birthday or baby shower gift available. Expecting parents will be so grateful and the birthday girl/guy will you put extra care into their gift.</p>
            </div>
        <!-- </a> -->
    </div>
    <div class="package">
        <!-- <a href="unity-sand-ceremony-vows.php"> -->
            <img src="<?php echo $this->getSkinUrl('images/banner_anniversary.jpg') ?>" width="176" height="123" border="0" alt="Anniversaries" />
            <div class="blue">
                <h2>Anniversaries</h2>
                <p>Anniversary celebrations are made even more memorable when a photo of the event is joined by decorative sand art and personal momentos.</p>
            </div>
        <!-- </a> -->
    </div>
</section> <!-- end packageDeals -->