var $j=jQuery.noConflict();(function($j){$j.fn.mageBox=function(opt){opt=jQuery.extend({my_speed:null,close_speed:300,bg_alpha:0.5,close_all:'.mage_close,.mage_overlay',slideShow:null,slideSpeed:null},opt);function start_magebox(){var corners='<tr>'+'<td colspan="3" class="magebox_up"></td>'+'</tr>'+'<tr>'+'<td class="t_l"></td>'+'<td class="t_c"></td>'+'<td class="t_r"></td>'+'</tr>'+'<tr>'+'<td class="c_l"></td>'+'<td class="c_c"><span><span></span></span><div></div></td>'+'<td class="c_r"></td>'+'</tr>'+'<tr>'+'<td class="b_l"></td>'+'<td class="b_c"></td>'+'<td class="b_r"></td>'+'</tr>'+'<tr>'+'<td colspan="3" class="magebox_down"></td>'+'</tr>';var window_height=$j(document).height();var bg_overlay=$j(jQuery('<div class="mage_overlay"></div>').hide().css({'opacity':+opt.bg_alpha,'height':window_height+'px'}));var main_cont=$j(jQuery('<table class="magebox_content" cellpadding="0" cellspacing="0"></table>'));var caption=$j(jQuery('<div class="caption"></div>'));var mage_nav=$j(jQuery('<div class="mage_nav"></div>'));var mage_close=$j(jQuery('<a href="#close" class="mage_close" title="close"></a>'));var mage_play=$j(jQuery('<a href="#play" class="play" title="play slideshow"></a>'));var mage_stop=$j(jQuery('<a href="#stop" class="stop" title="stop slideshow"></a>'));var mage_prev=$j(jQuery('<a href="#prev" class="mage_prev" title="previous image"></a>'));var mage_next=$j(jQuery('<a href="#next" class="mage_next" title="next image"></a>'));$j('body').append(bg_overlay).append(main_cont);main_cont.append(corners);$j('.magebox_up').append(mage_close);$j('.magebox_down').append(mage_nav);$j('.magebox_down').append(mage_play);mage_play.hide();$j('.magebox_down').append(mage_prev).append(mage_next);mage_nav.append(caption);var my_nav_w=mage_prev.width();main_cont.hide();var my_gall_classes=$j("a[class^='magebox']");var map=new Object();for(var i=0;i<my_gall_classes.length;i++){var it=$j(my_gall_classes[i])
map['a.'+it.attr('class')]=0;}
var gall_settings=new Array();for(var key in map){gall_settings.push(key);}
for(var i=0;i<gall_settings.length;i++){$j(gall_settings[i]).each(function(rel){this.rel=rel+1+" / "+$j(gall_settings[i]).length;});var add_first=$j(gall_settings[i]+':first').addClass('first');var add_last=$j(gall_settings[i]+':last').addClass('last');}
$j(my_gall_classes).each(function(rev){this.rev=rev+0});var imgCache=$j(my_gall_classes).each(function(){this.href});var hidden=$j('body').append('<div id="imgCache" style="display:none"></div').children('#imgCache');$j.each(imgCache,function(i,val){$j('<div/>').css({'background':'url('+val+')'}).appendTo(hidden);});var mage_gallery=$j(my_gall_classes);$j.fn.fixPNG=function(){return this.each(function(){var image=$j(this).css('backgroundImage');if(image.match(/^url\(["']?(.*\.png)["']?\)$/i)){image=RegExp.$1;$j(this).css({'backgroundImage':'none','filter':"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod="+($j(this).css('backgroundRepeat')=='no-repeat'?'crop':'scale')+", src='"+image+"')"}).each(function(){var position=$j(this).css('position');if(position!='absolute'&&position!='relative')
$j(this).css('position','relative');});}});};$j.browser.msie6=($j.browser.msie&&/MSIE 6\.0/i.test(window.navigator.userAgent));if($j.browser.msie6&&!/MSIE 8\.0/i.test(window.navigator.userAgent)){$j('.t_l,.t_c,.t_r,.c_l,.c_r,.b_l,.b_c,.b_r,a.mage_next, a.mage_prev,a.mage_prev_out,a.mage_next_out,.c_c,.mage_close,a.play,a.stop').fixPNG();var ie_w_h=$j(document).height();bg_overlay.css('height',ie_w_h+'px');}
if($j.browser.msie){opt.close_speed=0;}
$j(window).resize(function(){var new_w_bg=$j(document).height();bg_overlay.css({'visibility':'visible','height':+new_w_bg+'px'});});mage_prev.add(mage_next).bind('click',function(c){c.preventDefault();var image_count=parseInt($j(mage_gallery).filter('.item').attr('rev'));var start=$j(this).is('.mage_prev_out,.mage_prev')?$j(mage_gallery).eq(image_count-1):$j(mage_gallery).eq(image_count+1);if(!start.size()){start=$j(this).is('.mage_prev_out,.mage_prev')?$j(mage_gallery).eq($j(mage_gallery).size()-1):$j(mage_gallery).eq(0);}
start.click();mage_close.add(caption).add(mage_next).add(mage_prev).css('visibility','hidden');});$j(mage_gallery).each(function(array){var item=$j(this);item.unbind();item.bind('click',function(c){c.preventDefault();mage_open(item.attr('href'));var this_url=item.attr('href');var descr=item.attr('title');var number=item.attr('rel');if(descr==""){caption.html('<p>'+this_url+'<em class="number">'+number+'</em><a href='+this_url+' class="link_to" target="_blank" title="Open Image in a new window"></a></p>');}else{caption.html('<p>'+descr+'<em class="number">'+number+'</em><a href='+this_url+' class="link_to" target="_blank" title="Open Image in a new window"></a></p>');}
if(item.is('.last')){$j('.number').css('text-decoration','underline');}else{$j('.number').css('text-decoration','none');}
if(item.is('.first')){mage_prev.hide();mage_next.show();}else{mage_next.add(mage_prev).show();}
if(item.is('.last')){mage_prev.show();mage_next.hide();mage_play.css('width','0');}else{mage_play.css('width','40px');}
if(item.is('.last')&&item.is('.first')){mage_prev.add(mage_next).hide();$j('.number').hide();mage_play.remove();}
$j(mage_gallery).filter('.item').removeClass('item');item.addClass('item');$j('.c_c').removeClass('unique');});});var mage_open=function(my_url){mage_play.add(mage_stop).hide();mage_close.add(caption).add(mage_next).add(mage_prev).css('visibility','hidden');if(main_cont.is(':visible')){$j('.c_c div').children().fadeOut(300,function(){$j('.c_c div').children().remove();load_img(my_url);});}else{$j('.c_c div').children().remove();main_cont.show();bg_overlay.fadeIn(300,function(){load_img(my_url);});}}
var load_img=function(my_url){if(main_cont.is('.loading')){return;}
main_cont.addClass('loading');var img=new Image();img.onerror=function(){var main_cont_h=$j(main_cont).height();main_cont.css({marginTop:parseInt($j(document).scrollTop())-(main_cont_h/1.9)});$j('.c_c div').append('<p class="err_mess">There seems to be an Error: <a href="#close" class="close_magebox">Close MageBox</a></p>');$j('.close_magebox').bind('click',function(c){c.preventDefault();mage_close.add(bg_overlay).add(main_cont).add(caption).add(mage_next).add(mage_prev).hide(0,function(){img.src='';});main_cont.removeClass('loading');});}
img.onload=function(){var imgH=img.height;var imgW=img.width;var main_cont_h=$j(main_cont).height();var w_H=$j(window).height();var w_W=$j(window).width();$j(img).height(imgH).width(imgW).hide();$j('.c_c div').animate({height:imgH+'px',width:imgW+'px'},opt.my_speed);var fix=imgH/w_H*2.3;if(w_H<imgH){h_fix=fix;}else{h_fix=2;}
main_cont.animate({height:(imgH+40)+'px',width:(imgW+40)+'px',marginLeft:'-'+((imgW)/2+20)+'px',marginTop:parseInt($j(document).scrollTop())-(imgH/h_fix)},opt.my_speed,function(){$j('.mage_nav,.caption').css({width:(imgW)+'px','margin-bottom':'10px'});$j('.mage_nav').css('margin-left','-'+(imgW)/2+'px');var caption_height=caption.height();$j('.c_c div').append(img);mage_close.css('display','block');mage_next.add(mage_prev).add(mage_close).css('visibility','visible');caption.css({'visibility':'visible','display':'block','opacity':'0.8','overflow':'hidden'});main_cont.hover(function(){caption.stop().fadeTo(200,0.8);},function(){caption.stop().fadeTo(200,0);});$j(img).fadeIn(300);main_cont.removeClass('loading');if(opt.slideShow===true){mage_play.add(mage_stop).show();}else{mage_play.add(mage_stop).hide();}});}
img.src=my_url;$j('html').bind("keyup",function(c){if(c.keyCode==27){c.preventDefault();if($j(img).is(':visible')||$j('.c_c>div>p>a').is('.close_magebox')){$j(mage_gallery).removeClass('slideshow').removeClass('item');mage_close.add(bg_overlay).add(main_cont).add(caption).add(mage_next).add(mage_prev).hide(0,function(){img.src='';});main_cont.removeClass('loading');clearTimeout(timer);$j(mage_gallery).children().removeAttr('class');$j('.stop').remove();$j('.c_c').append(mage_play);$j('.sc_menu').css('display','none');$j('ul.sc_menu li a').removeClass('img_active').css('opacity','0.4');mage_next.add(mage_prev).show().css({'top':'50%'});$j(mage_gallery).children().fadeTo(100,1);}}});$j('html').bind("keyup",function(e){if($j('.item').is('.first')){}else if(e.keyCode==37){e.preventDefault();if($j(img).is(':visible')){clearTimeout(timer);$j(mage_gallery).children().removeAttr('class');$j('.stop').remove();$j('.c_c').append(mage_play);mage_prev.click();}}});$j('html').bind("keyup",function(z){if($j('.item').is('.last')){}else if(z.keyCode==39){z.preventDefault();if($j(img).is(':visible')){clearTimeout(timer);$j(mage_gallery).children().removeAttr('class');$j('.stop').remove();$j('.c_c').append(mage_play);mage_next.click();}}});var win_h=$j(window).height();mage_stop.bind('click',function(x){x.preventDefault();clearTimeout(timer);$j(mage_gallery).removeClass('slideshow');$j('.stop').remove();$j('.magebox_down').append(mage_play);mage_next.add(mage_prev).css('width',my_nav_w+'px');});mage_play.bind('click',function(w){w.preventDefault();clearTimeout(timer);if($j(img).is(':visible')){$j(mage_gallery).addClass('slideshow');$j('.play').remove();$j('.magebox_down').append(mage_stop);}
mage_next.add(mage_prev).css({'width':'0px'});return slideshow();});$j(opt.close_all).bind('click',function(c){$j(mage_gallery).removeClass('slideshow');clearTimeout(timer);if($j(img).is(':visible')){c.preventDefault();mage_close.add(bg_overlay).add(main_cont).add(caption).add(mage_next).add(mage_prev).hide(0,function(){img.src='';});main_cont.removeClass('loading');$j(mage_gallery).removeClass('slideshow');mage_next.add(mage_prev).css('width',my_nav_w+'px').hide();$j('.stop').remove();$j('.magebox_down').append(mage_play);mage_play.hide();}});if(opt.slideShow===true){function slideshow(){if($j(mage_gallery).filter('.item').is('.last')){clearTimeout(timer);$j(mage_gallery).removeClass('slideshow');$j('.stop').remove();$j('.magebox_down').append(mage_play);mage_next.add(mage_prev).css('width',my_nav_w+'px');}else if($j(mage_gallery).is('.slideshow')&&$j(img).is(':visible')){clearTimeout(timer);mage_next.click();}}
var timer=setInterval(slideshow,opt.slideSpeed*1000);}}}
start_magebox();}})(jQuery);