<section class="left-col">
    <h1>About Us</h1>
    <article>
        <h2>FROM BILL & ELAINE KENDALL</h2>
        <img src=<?php echo $this->getSkinUrl('images/about-us2.jpg') ?> title="Sand Colors: White and Ocean Blue" alt="The Forever Frame" />
        <p>We have shaped our business around forming honest relationships with our customers. Whatever works best for you makes us happy. This business started because I was a bride planning my own destination beach wedding. I spent months looking for a sand frame or shadow box and never found it. I ended up making one from a normal shadow box that was fine at the ceremony but then the sand immediately mixed and I was devastated.</p>

        <p>We developed The Forever Frame to remain looking the same as the day you fill it for years to come. We truly appreciate our customers and love helping to make your day as easy and special as possible.</p>

        <h2>OUR MISSION</h2>
        <p>Our frame and business will always have loving energy and positive customer relationships. We intend to be the primary provider of high quality sand frames with a Forever Frame in every household displaying a unique, personal, lasting memory.</p>

        <h2>OUR HISTORY</h2>
        <p>Since we were planning to get married on the beach in South Lake Tahoe,  we thought a unity ceremony would be a great idea for our beach  wedding. We wanted to incorporate a unity sand ceremony, but didn&rsquo;t want the typical vase that just seemed so over done and too common. We wanted something different and unique that we could keep forever.</p>
        <p>We spent weeks looking for a shadow box frame that would hold the unity sand as well as a photo, but couldn&rsquo;t find one. We ended up building one from a cheesy shadow box we found at Michael&rsquo;s. After a bit of trial and error we came up with a sand frame that we were excited to use at our wedding.</p>
        <p>After the ceremony, dozens of friends, family and even vendors asked us about the sand frame. It dawned on us that other engaged couples were probably searching unsuccessfully for a sand frame just as we had done. We then realized we had stumbled onto a business idea that would help couples reduce the stress of creating their perfect day, incorporate the most unique sand ceremony vessel into  their own wedding ceremony and keep a lasting memory intact forever. The concept of The Forever Frame was born.</p>
        <p>Now, as wonderful as our homemade shadow box frame was during the ceremony, afterward was a completely different story. The frame leaked sand (and still does to this day), the sand colors mixed together almost immediately and there was no way to exchange the photo with one of the ceremony without dumping out the sand entirely. So, even though we had a good idea, we knew we would need to perfect the concept. So we figured out what worked, what didn&rsquo;t, what we liked and what was missing. Several prototypes later, The Forever Frame was perfected.</p>
        <p>We are humbled by those of you who choose our frame to symbolize your unity. As you pour your sand into The Forever Frame, the colors will join together in a beautiful formation, never to be replicated. Just as your union can never be separated, neither can the grains of sand. We are very proud of The Forever Frame and love to see the way our  customers come up with unique ways to use it in their own sand ceremony.</p>

        <h2>OUR BUSINESS MODEL</h2>
        <p>The Forever Frame is a premier provider of unity sand frames to be used in weddings of any faith during a unity ceremony, as a graduation gift, anniversary gift or any special occasion. Through our direct business model, design and manufacturing, The Forever Frame provides products and services that fill a very specific and important customer desire and need.</p>
    </article>
</section> <!-- end left-col -->