<section class="left-col">
    <h1>Frequently Asked Questions</h1>
    <article>

        <!-- <img src=<?php echo $this->getSkinUrl('images/about-us2.jpg') ?> title="Sand Colors: White and Ocean Blue" alt="The Forever Frame" /> -->

        <object codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="352" height="550">
            <param name="movie" value="<?php echo $this->getSkinUrl('flash/FF_How_To.swf') ?>">
            </param>
            <param name="wmode" value="transparent"></param>
            <param name="allowFullScreen" value="true"></param>
            <param name="" value="always"></param>
            <param name="" value="true"></param>
            <embed src="<?php echo $this->getSkinUrl('flash/FF_How_To.swf') ?>" 
            type="application/x-shockwave-flash" allowscriptaccess="always" 
            wmode="transparent"  allowFullScreen="true" width="352" height="550">
            </embed>
        </object>

        <h2>Can I swap out the photo without disturbing the sand?</h2>
        <p>ABSOLUTELY YES. We had that in mind while we were developing this frame. You can <a href="http://www.theforeverframe.com/tips.php">change the picture</a> the day after the ceremony or 5 years later. The sand will be the same.</p>

        <h2>How does The Forever Frame&trade; work?</h2>
        <p>See the short video at the right for a step-by-step demonstration of how The Forever Frame&trade; works.</p>
        <ol id="faqlist">
            <li>Slide the lid off</li>
            <li>Remove the Keeper Plate</li>
            <li>Slide out the removable photo glass pane</li>
            <li>Attach Photo squares to the corners of your chosen photo</li>
            <li>Affix photo to the photo glass pane</li>
            <li>Slide photo glass pane back into the Forever Frame</li>
            <li>Fill with sand at your unity sand ceremony</li>
            <li>Insert Keeper Plate after the ceremony</li>
            <li>Replace lid</li>
            <li>Swap out the photo any time with the professional shots from your wedding</li>
        </ol>

        <h2>Can I fill the frame to the top with sand and place the photo in front of the sand?</h2>
        <p>YES. The removable glass photo pane allows the photo to be in front of the sand or behind. It is your choice.</p>

        <h2>If I want to fill the frame to the top with unity sand, how much will I need?</h2>
        <p>You will need 7 cups of sand. That translates to around 7 1-lb. bags.</p>

        <h2>What size picture will The Forever Frame&trade; hold?</h2>
        <p>Photo squares are included with the frame so any size photo up to an 8 x 10 can be used, as well as a few small photos at once, however we recommend a 5 x 7 photo for portrait orientation and a 4 x 6 photo for landscape orientation.</p>

        <h2>How do I mount the photo in The Forever Frame&trade;?</h2>
        <p>Clear adhesive Photo Mounting Corners (picture squares) are included in the frame. The rear pane of glass slides out. Place a photo square on each corner of the photo you will use. Position the photo taking into account that sand will fill the bottom 1/3 of the frame. Press the corners to adhere the photo to the glass.</p>

        <h2>How much does The Forever Frame&trade; weigh?</h2>
        <p>Without sand the frame weighs 5 lbs. With 2 and 1/4 cups of sand the frame weighs 6.5 lbs. </p>

        <h2>What are the dimensions of The Forever Frame&trade;?</h2>
        <p>The outer dimension of the frame is 11.25" x 9" x 3".</p>
        
        <h2>What is the cost of shipping The Forever Frame&trade;?</h2>
        <p>We use the US Postal Service and charge shipping according to the weight of the order (which depends on the inclusion of sand or vessels) and the postal code and/or country where it is being shipped.&nbsp;  You can estimate the cost of your shipping by going to the &rsquo;Shop&rsquo; page, add your desired products to the cart and use the Estimate Shipping tool.  If you have certain questions, please email <a href="mailto:elaine@theforeverframe.com" target="_blank">elaine@theforeverframe.com</a> for specific shipping prices.</p>

    </article>
</section> <!-- end left-col -->