<section class="cf">
    <div id="slideContainer" class="cf">
        <h1>The Forever Frame</h1>
        <div id="slides">
            <img src="<?php echo $this->getSkinUrl('images/IMG_2025_edit.jpg') ?>" width="457" height="327" alt="compare framette">
            <img src="<?php echo $this->getSkinUrl('images/IMG_1987_edit.jpg') ?>" width="457" height="327" alt="framettes">
            <img src="<?php echo $this->getSkinUrl('images/pic6.jpg') ?>" width="457" height="327" alt="pic6"> 
            <img src="<?php echo $this->getSkinUrl('images/pic7.jpg') ?>" width="457" height="327" alt="pic7"> 
            <img src="<?php echo $this->getSkinUrl('images/pic10.jpg') ?>" width="457" height="327" alt="pic10"> 
            <img src="<?php echo $this->getSkinUrl('images/pic1.jpg') ?>" width="457" height="327" alt="pic1"> 
            <img src="<?php echo $this->getSkinUrl('images/pic2.jpg') ?>" width="457" height="327" alt="pic2"> 
            <img src="<?php echo $this->getSkinUrl('images/pic12.jpg') ?>" width="457" height="327" alt="pic12"> 
            <img src="<?php echo $this->getSkinUrl('images/pic4.jpg') ?>" width="457" height="327" alt="pic4"> 
            <img src="<?php echo $this->getSkinUrl('images/pic9.jpg') ?>" width="457" height="327" alt="pic9"> 
            <img src="<?php echo $this->getSkinUrl('images/pic5.jpg') ?>" width="457" height="327" alt="pic5">
        </div> <!-- end slides -->
    </div> <!-- end slideContainer -->

    <div class="create">
        <div>
            <h2><a href="http://www.foreverframe.com/products/forever-frame/forever-frame.html">Create Your Frame</a></h2>
        </div>
        <ul>
            <li>The Perfect Sand Shadow Box</li>
            <li>Prevents Sand From Mixing</li>
            <li>Perfect for Travel</li>
            <li>Exchange Photos Any Time</li>
            <li>Extremely Versatile</li>
        </ul>
        <script src='//www.weddingwire.com/assets/vendor/widgets/ww-rated-2013.js' type='application/javascript'></script><div id='ww-widget-wwrated-2013'><a class="ww-top" href="http://www.weddingwire.com" target="_blank" title="Weddings, Wedding, Wedding Venues"></a><a class="ww-bottom" href="http://www.weddingwire.com/reviews/the-forever-frame-gilbert/cfa97f7c8fd3cdc3.html" target="_blank" title="The Forever Frame Reviews, Phoenix  Favors &amp; Gifts"></a></div><script>  WeddingWire.ensureInit(function() {WeddingWire.createWWRated2013({"vendorId":"cfa97f7c8fd3cdc3" }); });</script>
        <p><a href="http://www.favourlicious.ca" target="_blank">CANADIAN CUSTOMERS</a> SAVE SHIPPING AND CUSTOMS CHARGES!</p>
    </div> <!-- end create -->
</section>

<section id="packageDeals" class="cf">
    <h1>Keepsake Ideas</h1>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_wedding.jpg') ?>" width="176" height="123" border="0" alt="Unity Sand Ceremonies">
        <div class="callout">
            <p>Unity Sand Ceremonies</p>
        </div>
    </div>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_shadowbox.jpg') ?>" width="176" height="123" border="0" alt="Shadow Box Frame" />
        <div class="callout">
            <p>Shadow Box</p>
        </div>
    </div>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_graduation.jpg') ?>" width="176" height="123" border="0" alt="Graduations" />
        <div class="callout">
            <p>Graduations</p>
        </div>
    </div>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_birthday.jpg') ?>" width="176" height="123" border="0" alt="Birthday / Baby Shower" />
        <div class="callout">
            <p>Birthday/Baby Shower</p>
        </div>
    </div>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_anniversary.jpg') ?>" width="176" height="123" border="0" alt="Anniversaries" />
        <div class="callout">
            <p>Anniversaries</p>
        </div>
    </div>
    <div class="package">
        <img src="<?php echo $this->getSkinUrl('images/banner_baby.png') ?>" width="176" height="123" border="0" alt="Anniversaries" />
        <div class="callout">
            <p>Adoption Ceremonies</p>
        </div>
    </div>
</section> <!-- end packageDeals -->

<section class="compare cf">
    <h2>See for Yourself. <br>Compare the Competition!</h2>
    <iframe id="featureCompare" width="551" height="310" src="//www.youtube.com/embed/08WF3VkO0sY" frameborder="0" allowfullscreen></iframe>
</section> <!-- end compare -->