<section class="left-col">
    <h1>Instructions</h1>
    <article class="manual">
        <h2>Check out our Instructional Video!</h2>
        <iframe id="instructVideo" width="678" height="381" src="//www.youtube.com/embed/iXDsE9IoMk8" frameborder="0" allowfullscreen></iframe>
        <div class="instructLeft cf">
            <img src="<?php echo $this->getSkinUrl('images/instructions_step1.jpg') ?>">
            <div class="instructions">
                <h2>Step 1</h2>
                <p>Affix a photo to rear glass using included photo mounts. Exchange picture any time without disturbing the sand.</p>
            </div>
        </div>
        <div class="instructRight cf">
            <div class="instructions">
                <h2>Step 2</h2>
                <p>Pour sand by alternating each pour to achieve an artful pattern.</p>
            </div>
            <img src="<?php echo $this->getSkinUrl('images/instructions_step2.jpg') ?>">
        </div>
        <div class="instructLeft cf">
            <img src="<?php echo $this->getSkinUrl('images/instructions_step3.jpg') ?>">
            <div class="instructions">
                <h2>Step 3</h2>
                <p>Insert included Keeper Plate to lock sand in place & preserve your design.</p>
            </div>
        </div>
        <div class="instructRight cf">
            <div class="instructions">
                <h2>Step 4</h2>
                <p>Slide the lid into place.</p>
            </div>
            <img src="<?php echo $this->getSkinUrl('images/instructions_step4.jpg') ?>">
        </div>
        <div class="instructLeft cf">
            <img src="<?php echo $this->getSkinUrl('images/instructions_step5.jpg') ?>">
            <div class="instructions">
                <h2>Step 5</h2>
                <p>Display your unique frame as a reminder of the special occasion.</p>
            </div>
        </div>

        <div class="fillInstructions">
            <h2>Please Read These Instructions Completely</h2>

            <h3>Pre-Ceremony</h3>
            <ol>
                <li>Select sand colors and pouring containers.</li>
                <li>Measure each color of sand into a container according to the chart below.</li>
                <h4>Fill Frame to Keeper Plate</h4>
                <table class="frameFill">
                    <tr>
                        <th># Colors Used</th>
                        <th>Cups (2 1/4 total)</th>
                        <th>Ounces (18 total)</th>
                        <th>Grams (510 total)</th>
                        <th>Liters (0.53 total)</th>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>1 1/8</td>
                        <td>9</td>
                        <td>255</td>
                        <td>0.27</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>3/4</td>
                        <td>6</td>
                        <td>170</td>
                        <td>0.18</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>4/7</td>
                        <td>4.5</td>
                        <td>128</td>
                        <td>0.13</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>4/9</td>
                        <td>3.6</td>
                        <td>102</td>
                        <td>0.11</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>3/8</td>
                        <td>3</td>
                        <td>85</td>
                        <td>0.09</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>1/3</td>
                        <td>2.6</td>
                        <td>74</td>
                        <td>0.08</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>3 5/9</td>
                        <td>2.3</td>
                        <td>65</td>
                        <td>0.07</td>
                    </tr>
                </table>
                <h4>Fill frame to Top</h4>
                <table class="frameFill">
                    <tr>
                        <th># Colors Used</th>
                        <th>Cups (7 total)</th>
                        <th>Ounces (56 total)</th>
                        <th>Grams (1588 total)</th>
                        <th>Liters (1.66 total)</th>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>3 1/2</td>
                        <td>28</td>
                        <td>794</td>
                        <td>0.85</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>2 1/3</td>
                        <td>18.7</td>
                        <td>530</td>
                        <td>0.57</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>1 3/4</td>
                        <td>14</td>
                        <td>397</td>
                        <td>0.43</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>1 2/5</td>
                        <td>11.2</td>
                        <td>318</td>
                        <td>0.34</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>1 1/6</td>
                        <td>9.3</td>
                        <td>264</td>
                        <td>0.28</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>1</td>
                        <td>8</td>
                        <td>227</td>
                        <td>0.24</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>1 1/7</td>
                        <td>7</td>
                        <td>198</td>
                        <td>0.27</td>
                    </tr>
                </table>
                <p>NOTE:  You MUST use the correct amount of sand to ensure the Keeper Plate™ fits. It is better to under-fill than over-fill. You can always add more after the ceremony.</p>
                <li>Set up The Forever Frame at the ceremony so it’s visible to your guests during the ceremony.</li>
                <li>Remove the Keeper Plate™ and lid from frame and place them out of site behind the frame. DO NOT LOSE THE KEEPER PLATE.</li>
                <li>Delegate someone you trust to take care of your Forever Frame after the ceremony, i.e., Maid of Honor, a bride’s maid, Best Man, a groomsman or family member. Make sure they know that the Keeper Plate™ should NOT be thrown away or lost.</li>
            </ol>

            <h3>During Ceremony</h3>
            <ol>
                <li>Take turns slowly pouring each different color of sand into the sealed chamber.</li>
                <li>Have the officiant or special someone read a prepared dialogue while pouring to make it more special.</li>
            </ol>

            <h3>Post Ceremony</h3>
            <ol>
                <li>Your chosen Forever Frame steward will need to follow these simple steps:</li>
                    <ul>
                        <li>Gently move The Forever Frame side to side to level out the sand.</li>
                        <li>Insert the Keeper Plate.</li>
                        <li>Slide on the Lid.</li>
                    </ul>
                <li>Add keepsakes from the ceremony or reception to the frame (champagne cork, match book, flower petals, etc.)</li>
            </ol>

            <h3>Travel Home</h3>
            <ol>
                <li>CARRY the frame in an UPRIGHT position at all times as a carry-on in a back pack or separate bag. Do NOT store it lying down under the seat or in the overhead.</li>
            </ol>
            <p>NOTE: Although the Keeper Plate™ will prevent the sand from moving freely, it will not hold up to jarring, shaking or banging around.</p>
            <p>When you receive your wedding photos, you can exchange the photo used at the ceremony with a professional photo. </p>
        </div> <!-- end fillInstructions -->
    </article>
</section> <!-- end left-col -->