<section class="left-col">

    <h1>Policies and Your Privacy</h1>

    <article>
        <h2>TURNAROUND TIME</h2>
        <p>Most orders are completed and shipped within 2-3 business days starting the day after the order is placed, though this is not guaranteed. Engraving and special orders can delay shipping by an additional 2-3 days. Once your frame order has shipped, it can take 3-6 business days to deliver within the US and up to 10 days outside the US to receive the order, depending on your location. If you have a deadline, please let us know by replying to your confirmation email after you place your order. We will do our best to meet your deadline and if we feel we cannot, we'll contact you to discuss more expedited shipping methods.</p>

        <h2>SHIPPING DAMAGE POLICY</h2>
        <p>If a frame arrives damaged or engraved incorrectly due to our error, we will replace it at no cost to you. You must notify us within 3 days after having received your order by email at elaine@theforeverframe.com and be sure to include photos of the damage or engraving error. We will send you a replacement along with instructions on how to return the frame. Notifications of damage or error received after 2 weeks of receipt of frame will not be replaced free of charge. Customer will be responsible for shipping both ways as well as 50% cost of frame plus engraving.</p>

        <h2>RETURN POLICY</h2>
        <p>Custom engraved frames may not be returned. Non-customized frames can be returned for a full refund of the cost of the frame as long as it is shipped by by USPS Priority service and packed properly to avoid breakage. Once the returned frame is received without breakage we will refund the purchase price less the original shipping cost. The intent to return MUST BE communicated within 3 weeks of having received your frame. We MUST receive an email to elaine@theforeverframe.com informing us of your intent to return. We will provide the proper return address to ship the frame back to us. Customers are responsible for returning the frame.</p>

        <h2>CANCELLATION/REFUND POLICY</h2>
        <p>Custom engraved frames may not be returned unless there is an error in the engraving due to our negligence. Non-customized frames, sand and non-customized vessels can be returned for a full refund of the original cost less shipping as long as it is shipped back to us by USPS Priority Service or UPS 2 Day service and packed properly to avoid breakage. Once the returned item(s) is received without breakage, we will refund the purchase price less the original shipping cost. The intent to return MUST BE communicated within two (2) weeks of having received your order. We MUST receive an email to elaine@foreverframe.com or a direct call to 480-650-9634 or 480-861-4410 with intent to cancel. Orders can only be canceled if they have not been shipped. We will send an email confirmation with the shipping tracking number within 2 days of receiving your order.</p>

        <h2>AGREEMENT BETWEEN USER AND THE FOREVER FRAME</h2>
        <p>Welcome to www.foreverframe.com. The www.foreverframe.com website (the "Site") is comprised of various web pages operated by The Forever Frame. The Site is offered to you conditioned on your acceptance without modification of the terms, conditions and notices contained herein (the "Terms"). Your use of www.foreverframe.com constitutes your agreement to all such Terms. Please read these terms carefully and keep a copy of them for your reference. www.foreverframe.com & www.theforeverframe.com are E-commerce sites. The purpose of our website is to provide retail sales of The Forever Frame unity sand frame, colored sand, pouring vessels and engraving services to a global market.</p>

        <h2>PRIVACY POLICY</h2>
        <p>We respect the privacy of our customers and the confidential nature of the information provided to us through the course of doing business. We never sell nor distribute any customer information to any third party. The only information provided externally is that which is needed to fulfill your order (i.e. shipping information). We do not store nor retain credit card numbers, except in cases where a business account is established. All transactions are done on our secure server using pages encrypted with 128 bit secure sockets layer (SSL) encryption.</p>

        <h2>ELECTRONIC COMMUNICATIONS</h2>
        <p>Visiting www.foreverframe.com or www.theforeverframe.com or sending emails to The Forever Frame constitutes electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures and other communications that we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communications be in writing.</p>

        <h2>YOUR ACCOUNT</h2>
        <p>If you use this Site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer and you agree to accept responsibility for all activities that occur under your account or password. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that the Forever Frame is not responsible for third party access to your account that results from theft or misappropriation of your account. The Forever Frame and its associates reserve the right to refuse or cancel service, terminate accounts or remove or edit content at our sole discretion.</p>
        <p>The Forever Frame does not knowingly collect, either online or offline, personal information from persons under the age of thirteen. IF you are under 18, you may use www.foreverframe.com only with permission of a parent or guardian.</p>

        <h2>INFORMATION THAT IS GATHERED FROM VISITORS</h2>
        <p>In common with other websites, log files are stored on the web server saving details such as the visitor's IP address, browser type, referring page and time of visit.</p>
        <p>Cookies may be used to remember visitor preferences when interacting with the website.</p>
        <p>Where registration is required, the visitor's email and a username will be stored on the server.</p>

        <h2>HOW THE INFORMATION IS USED</h2>
        <p>The information is used to enhance the vistor's experience when using the website to display personalised content and possibly advertising.</p>

        <p>E-mail addresses will not be sold, rented or leased to 3rd parties.</p>

        <p>E-mail may be sent to inform you of news of our services or offers by us or our affiliates.</p>

        <h2>VISITOR OPTIONS</h2>
        <p>If you have subscribed to one of our services, you may unsubscribe by following the instructions which are included in e-mail that you receive.</p>
        <p>You may be able to block cookies via your browser settings but this may prevent you from access to certain features of the website.</p>

        <h2>COOKIES</h2>
        <p>Cookies are small digital signature files that are stored by your web browser that allow your preferences to be recorded when visiting the website. Also they may be used to track your return visits to the website.</p>
        <p>3rd party advertising companies may also use cookies for tracking purposes.</p>

        <h2>GOOGLE ADS</h2>
        <p>Google, as a third party vendor, uses cookies to serve ads.</p>
        <p>Google's use of the DART cookie enables it to serve ads to visitors based on their visit to sites they visit on the Internet.</p>
        <p>Website visitors may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>

    </article>

</section> <!-- end left-col -->
