<section class="left-col">

    <h1>Testimonials</h1>
        <!-- <h2 id="test">Customers are raving about The Forever Frame&trade;. See what some of them have to say:</h2> -->
    <article class="cf">
        <header class="cf">
            <h3>This is from an amazing and extremely creative bride in Oregon</h3>
            <p class="date"></p>
        </header>
        <p>Our frame turned out beautifully, thank you!</p>
        <p>We used sand from the beach and it was slightly damp, which we quickly learned wouldn&rsquo;t work (during our ceremony) but when we got home we mixed the two colors together that we used during the ceremony for the very top layer. Mainly because we wanted to use sand from the actual ceremony, but also because it was completely mixed together and we liked the symbolism.</p>
        <p>We added crystal beads from the custom made crystal backdrop curtain inside, as well as a pearl strand that came from our cake, a few dried flower petals and feathers our flowergirls used, and as a gift I received blessed dirt from some scared place that&rsquo;s supposed to bring good luck and happiness. I scattered some of that in there as well. We didn&rsquo;t want the back to be bare so we used the love notes that were attached to the his and her gifts we gave eachother before the wedding ceremony privately. We thought most people who come to visit us and see our frame won&rsquo;t pick it up so see the back so it&rsquo;s still a little something for just us. We know its back there.</p>
        <p>Feel free to use these images. If you do, please let us know. We&rsquo;d love to see them on your website :)</p>
        <ul class="cf">
            <li><a href="http://i906.photobucket.com/albums/ac266/ekendall01/The%20Forever%20Frame%20Customer%20Photos/76caf513-35c6-4bbf-a5ba-2e7436323d7c_zpsc7e7db65.jpg" class="lightbox_trigger"><img src="http://i906.photobucket.com/albums/ac266/ekendall01/The%20Forever%20Frame%20Customer%20Photos/76caf513-35c6-4bbf-a5ba-2e7436323d7c_zpsc7e7db65.jpg" alt="" /></a></li>
            <li><a href="http://i906.photobucket.com/albums/ac266/ekendall01/The%20Forever%20Frame%20Customer%20Photos/3ebd8434-bc65-40e4-8694-98a153daec4d_zpsc1681327.jpg" class="lightbox_trigger"><img src="http://i906.photobucket.com/albums/ac266/ekendall01/The%20Forever%20Frame%20Customer%20Photos/3ebd8434-bc65-40e4-8694-98a153daec4d_zpsc1681327.jpg" alt="" /></a></li>
        </ul>
        <footer>
            <p>Thanks again!</p>
            <p>The new Mrs. Bonilla-Ulep</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>From a customer that used our frame as a Family Vacation keepsake</h3>
            <p class="date">7/25/2013</p>
        </header>
        <div>
            <!-- <img src="http://i906.photobucket.com/albums/ac266/ekendall01/Customer-Vacation_zpseee0e5a2.jpg" border="0" alt=" photo Customer-Vacation_zpseee0e5a2.jpg" /> -->
        </div>
        <footer>
        </footer>
    </article>
 
    <article class="cf">
        <header class = "cf">
            <h3>From a bride in Indiana wth a custom graphic</h3>
            <p class="date">7/25/2013</p>
        </header>
        <p>I just received the frame and I absolutely LOVE it! It turned out  better than I imagined it would. I am so incredibly happy and will  definitely recommend you to friends and family.</p>
        <p>I really enjoyed  working with you and appreciate all of the attention to detail.</p>
        <footer>
            <p>Thanks</p>
            <p>Casey H.</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3></h3>
            <p class="date"></p>
        </header>
        <div>
            <img src="https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-prn1/1011826_538508206185938_1331319511_n.jpg" alt="" />
        </div>
        <footer>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>From a very creative customer in Vermont</h3>
            <p class="date">5/22/13</p>
        </header>
        <p>Hi Elaine!</p>
        <p>I received our frame in the mail, words  can not describe how wonderful it is! Thank you so much for the  personalized letter! If you would like I can send you a photo of our  completed Forever Frame for your customer photos.</p>
        <footer>
            <p>Thank you again! It was beautiful, well crafted and breathtaking!</p>
            <p>Kristina T.</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>From a wonderful customer that needed some special engraving in a hurry</h3>
            <p class="date">4/26/13</p>
        </header>
        <p>Hi Elaine,</p>
        <p>I just received the masterpiece! I can&rsquo;t  tell in words how much I love it! The engraving is exactly what I have  in my mind! The packaging is also very great!</p>
        <p>Thank  you again for making this for me! My husband and I love it very much! I  can imagine it will surprise and impress everyone in my wedding in  China. I&rsquo;ll share it with my friend and highly recommend it to anyone  who will get married.</p>
        <footer>
            <p>Again, thank you very much. It is my best shopping experience.</p>
            <p>Xin</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>From an amazing Amazon customer</h3>
            <p class="date">3/18/13</p>
        </header>
        <p>I just wanted to take a minute to let you know that this frame we  received is absolutely gorgeous!!! We bought this as a wedding present  for our cousin and she is thrilled with the results. I wasnt exactly  expecting it to be so big and solid (I didnt pay much attention as I  ordered what she wanted for her ceremony) but its breathtaking! The  engraving is beautiful too. Your accomodations to get that on there are  very appreciated.</p>
        <p>We didn't receive the keeper plate that was supposed to be included, but I  called the customer service and the gentleman that answered said he was right in the process of doing shipping and would get one out  mmediately!</p>
        <footer>
            <p>Thank you for this stunning product and it is a pleasure doing business with you!</p>
            <p>Heidi</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3></h3>
            <p class="date">2/15/13</p>
        </header>
        <p>I received our Forever Frame today. It is beautiful and very well constructed.  The engraving is a nice touch and the sand colors were true to the internet pictures. I can&rsquo;t believe how fast the shipping was! I will definitely recommend your company to anyone I know that is looking for an amazing unity sand idea!</p>
        <p>The theme for our wedding is all about music (invitations were old 45 records, table numbers are concert tickets, escort card holders are  treble clefs, etc.)</p>
        <p>We fell in love at a music festival and he proposed to me at one.</p>
        <p>He is actually getting that particular music note that was engraved on our frame put on his wedding band, so I was excited to see it as an option for engraving on your site.</p>
        <p>Thank you again for the wonderful product! It will be a cherished memory from our  special day for many years to come!</p>
        <footer>
            <p>From Jamie D. of Chicago, IL</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>From an excited and wonderful Aunt</h3>
            <p class="date">2/02/13</p>
        </header>
        <p>Elaine,</p>
        <p>My order arrived today...thank you! It is absolutely beautiful.</p>
        <p>The engraving detail is elegant. I can't wait until my niece's engagement party in a couple of weeks to show her..She does not know that I ordered her the Forever Frame! She and her fiance are going to love it!</p>
        <p>Thank you soooooooooooooooo much for your help and quick turn around time!</p>
       <!--  <div>
            <img src="https://mail.google.com/mail/images/cleardot.gif" alt="" />
        </div> -->
        <footer>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>A wonderful email from a bride in Illinois</h3>
            <p class="date"></p>
        </header>
        <p>We were so excited to have something that our son could join in on. Each of us had our own color and were able to pour them together into the frame. We recieved so many compliments on the frame and the beautiful idea.</p>
        <p>We have it on our mantle and I am just waiting to put a final wedding picture in it. Everytime my step-son sees it, he says, "We did that together." It was a very special moment for our family and is a wonderful reminder of how we all came together that day.</p>
        <p>Thank you for making this possible, it was just as I imagined, perfect!!</p>
        <div>
            <!-- <img src="http://i906.photobucket.com/albums/ac266/ekendall01/family.jpg" alt=""  /> -->
        </div>
        <footer>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
            <h3>A FaceBook post from a wonderful customer in Texas</h3>
            <p class="date"></p>
        </header>
        <p>Thank you again for our wonderful frame! Our day was wonderful & all our guests were so impressed with the sand ceremony. they had never seen it performed like this. It will be proudly displayed on our mantle. :-)</p>
        <div>
            <!-- <img src="http://i906.photobucket.com/albums/ac266/ekendall01/StacyKlimek-Arnold-1.jpg" alt="" /> -->
        </div>
        <footer>
        </footer>
    </article>

    <article class="cr">
        <header class="cf">
            <h3>A FaceBook post from a beautiful bride in Illinois</h3>
        </header>
        <p>We received our frame the other day and I just love it! It is such a  wonderful and smart idea!! I have been showing everyone! I can't wait  until we use it later this month at our wedding and I can post pictures. The owner was an absolute pleasure to work with and I can't thank her enough!</p>
        <footer>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>A FaceBook post from a wonderful customer in the Philippines</h3>
        <p class="date"></p>
        </header>
        <div>
            <img src="http://i906.photobucket.com/albums/ac266/ekendall01/P1100413.jpg" alt="" /><img 
            src="http://i906.photobucket.com/albums/ac266/ekendall01/P1100449.jpg" alt="" />
            <img src="http://i906.photobucket.com/albums/ac266/ekendall01/P1100483.jpg" alt="" />
        </div>
        <footer>
        </footer>
     </article>

    <article class="cf">
        <header class="cf">
        <h3>Wonderful unity sand kit</h3>
        <p class="date">8/25/2011</p>
      </header>
        <p>I love how the unity sand ceremony can be  incorporated with our favorite wedding photo. This unity sand frame kit  does that - great for displaying at home.</p>
        <footer>
            <p>Summer Bride</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>Great sand kit</h3>
        <p class="date">7/31/2011</p>
      </header>
        <p>This unity sand frame kit is a great combination of photo and unity wedding sand. Love the idea!</p>
        <footer>
            <p>June Bride</p>
        </footer>
  </article>

    <article class="cf">
        <header class="cf">
        <h3>Travel safe!</h3>
        <p class="date">7/19/2011</p>
      </header>
        <p>I love how the unity sand frame kit can travel  well. Can I also add some elements such as sea shells or sand dollars to  the design? I'm considering having a unity sand ceremony during my beach wedding.</p>
        <footer>
            <p>Paula F</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>Great for my destination wedding</h3>
        <p class="date">7/11/2011</p>
      </header>
        <p>I'm having a beach wedding and a unity sand ceremony. I'm just concerned that all that beautiful sand will be muddled up while traveling. This unity sand frame kit is what I have in  mind. It travels well and I can also put our favorite shot - what a  great keepsake!</p>
        <footer>
            <p>Joy G</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>A FaceBook post from a wonderful customer in Australia</h3>
        <p class="date"></p>
      </header>
        <p>I've just received the frame that will be used in the marriage ceremony for my son & his beautiful fianc&eacute; in January. I'm so glad I happened to find your site when searching for wedding items online...Huge thank you's from a very, very happy customer in Australia.</p>
        <footer>
            <p>Dianne</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>From Carrie-Ann in Canada</h3>
        <p class="date">8/19/2011</p>
      </header>
        <p>Thank you sooo much!! It worked this time and my order is placed!</p>
        <p>I was a little anxious about ordering online out of the country in the first place, but I can honestly say that your amazing costumer service and quick response to my emails completely put my mind at ease. I am so glad I came across The Forever Frame and can't wait to receive it.</p>
        <p>We really wanted something different for our sand blending ceremony and my fiance had just said, "Too bad we couldn't get some kind of picture frame or shadow box instead of a bottle" and now we have it!</p>
        <p>I can't thank you enough. You have been amazing</p>
        <footer>
            <p>Carrie-Ann</p>
        </footer>
    </article>

       <article class="cf">
        <header class="cf">
        <h3>From Jayne Hall in Scotland</h3>
        <p class="date"></p>
      </header>
        <p>Good Morning Elaine,<p>
        <p>I just wanted to say that my frame has arrived this morning and I am delighted with it. It will make a great addition to both our ceremony and also to our home.</p>
        <p>Thank you for all your help and your great service. I shall recommend you to anyone else who may be looking for something just a little bit more special for any occasion.</p>
        <footer>
            <p>Kind Regards,</p>
            <p>Jayne</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>From a wonderful customer</h3>
        <p class="date"></p>
      </header>
        <p>We received our Forever Frame and absolutely love it. So excited about our wedding and this part of our ceremony.</p>
        <p>We are bragging on your product every chance we get. We love it! We would be flattered to be posted on your blog, and will certainly send pics of the frame once filled, our live change forever on Oct, 15th, can't wait.</p>
        <footer>
            <p>All the best,</p>
            <p>Tom n Kim</p>
        </footer>
    </article>

    <article class="cf">
        <header class="cf">
        <h3>From an appreciative customer</h3>
        <p class="date"></p>
      </header>
        <p>The Sand Ceremony in the "Forever Frame!"</p>
        <div>
            <img title="The Forever Frame after the unity sand ceremony." src="http://i906.photobucket.com/albums/ac266/ekendall01/The%20Forever%20Frame%20Customer%20Photos/Nicki-RyanWilson.jpg" alt="Nicki &amp; Ryan Wilson" /></p>
        </div>
        <footer>
            <p>Congratulations to Mr. & Mrs. R</p>
        </footer>
    </article>

    <script>

    $j(document).ready(function() {
        $j( '.lightbox_trigger' ).click(function(e) {
            e.preventDefault();
            var image_href = $j(this).attr( "href" );
            console.log( $j(this) );

            if ($j( '#lightbox' ).length > 0) { // #lightbox exists
                // insert img tag with clicked link's href as src value
                $j( '#content' ).html( '<img src="' + image_href + '" />');
                // show lightbox window - you can use a transition here if you want, i.e.
                $j( '#lightbox' ).show();
            } else {
                // create HTML markup for lightbox window
                var lightbox = 
                '<div id="lightbox">' +
                    '<p>Click to close</p>' +
                    '<div id="content">' + // insert clicked link's href into img src
                        '<img src="' + image_href + '" />' +
                    '</div>' +
                '</div>';
                // insert lightbox HTML into page
                $j( 'body' ).append( lightbox );
            }
        });
        // Click anywhere on the page to get rid of lightbox window
        $j( '#lightbox' ).on("click", function() {
            $j( '#lightbox' ).hide();
        });
    });

    </script>

</section> <!-- end left-col -->