<section class="left-col">

    <h1>Helpful Hints for a Successful Unity Sand Ceremony</h1>
    <article>

            <object codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0" width="352" height="550">
                <param name="movie" value="<?php echo $this->getSkinUrl('flash/FF_How_To.swf') ?>">
                </param>
                <param name="wmode" value="transparent"></param>
                <param name="allowFullScreen" value="true"></param>
                <param name="" value="always"></param>
                <param name="" value="true"></param>
                <embed src="<?php echo $this->getSkinUrl('flash/FF_How_To.swf') ?>" 
                type="application/x-shockwave-flash" allowscriptaccess="always" 
                wmode="transparent"  allowFullScreen="true" width="352" height="550">
                </embed>
            </object>

            <h2>Use an officiant that is experienced and skilled in Unity Sand Ceremonies</h2>
            <p>Minister Larry James voted "Best Officiant" in 2007 and 2008 and the Reverand Giovanni voted Bride's Choice 2010 have been conducting <a href="../products.php">unity sand</a> ceremonies for over a decade. Visit <a href="http://www.celebrateintimateweddings.com" target="_blank">Celebrate Intimate Weddings</a> for Minister Larry James. Visit <a href="http://www.revgiovanni.com/RevGio/Welcome.html" target="_blank">Reverand Giovanni</a> for the Reverand Giovanni and get lots of ideas and information regarding incorporating a sand ceremony into your wedding!</p>
            
            <h2>Take turns pouring each color</h2>
            <p>Instead of pouring all at once together, take turns pouring each separate color a little at a time to get a more marbleized design.</p>

            <h2>Personalize the pouring vases for children</h2>
            <p>If this is a second marriage or even a first marriage where the children will join in the unity sand ceremony, consider having the pouring vase engraved with the children's names to help them feel even more a part of the event and retain a special keepsake from the big day.</p>

            <h2>For Destination Weddings, transport the frame home in a back pack or bag as a carry on in an upright position</h2>
            <p>Although the Keeper Plate will prevent the sand from mixing when the frame is moved, it will not withstand a baggage handler's abuse.  We strongly recommend that you transport the frame home as a carry on in an upright position to further ensure the sand remains as you poured it.</p>

            <h2>Choose a location easily visible to your guests.</h2>
            <p>Make sure you have an ideal spot picked out to place your Forever Frame.  A small table, which allows you to stand to both sides, is ideal.</p>

            <h2>Be creative with the sand ceremony display and setup.</h2>
            <p>You can place The Forever Frame&trade; and unity sand on the table prior to the unity ceremony starting, or have the mothers, flower girls or special guests place the <a href="../">sand vessels</a> by The Forever Frame as part of the entrance ceremony.</p>

            <h2>Include your parents, children or friends in the unity sand ceremony</h2>
            <p>Additional colors of sand can be used to symbolize a blending of families, your children or your guests.</p>
            <p>Have your chosen loved one join you in the ceremony to pour their color.</p>

            <h2>Use an accent color to symbolize your wedding location.</h2>
            <p>If using more than 2 colors, don't be afraid to pour an accent sand color into the frame prior to the ceremony if it fits your vision better.</p>
            <p>For example, a Sedona Arizona wedding may include a red or terracotta color below your design and when the ceremony is complete, the same color can be poured on top to complete the look.</p>

            <h2>Humidity can sometimes be an issue for a unity sand ceremony.</h2>
            <p>If you are using The Forever Frame&trade; bottles, ensure the corks are secured tightly to prevent moisture from mixing with the sand. If using a vessel with no top, have your Maid of Honor or Best Man take a moment to make sure the sand has not clumped prior to the ceremony.</p>

            <h2>Preserve your unity sand design in The Forever Frame&trade; so it won't move.</h2>
            <p>To keep the sand design the way it is the day of your wedding you will want to delegate someone prior to the ceremony to take care of your Forever Frame after the ceremony, i.e., Maid of Honor, a bride's maid, Best Man, a groomsman or family member.</p>
            <p>He/she will need to follow these simple steps:</p>
                <ol id="tips">
                    <li>Gently move The Forever Frame&trade; side to side to level out the sand.</li>
                    <li>Place the keeper plate&trade; in the sand chamber</li>
                </ol>
    
    </article>

</section> <!-- end left-col -->