<div class="grid12-9">
    <section>
        <h1>Frequently Asked Questions</h1>
        <article>
            <div class="collapsible">
                <h3 class="block-title">Can I swap out the photo without disturbing the sand?</h3>
                <div class="block-content">
                    <p>ABSOLUTELY YES. We had that in mind while we were developing this frame. You can <a href="http://www.foreverframe.com/instructions.html">change the picture</a> the day after the ceremony or 5 years later. The sand will be the same.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">How does The Forever Frame&trade; work?</h3>
                <div class="block-content">
                    <p>See our <a href="http://www.foreverframe.com/instructions.html">instructions page</a> for information on how The Forever Frame&trade; works.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">What is the difference between the Forever Frame and the Forever Framette?</h3>
                <div class="block-content">
                    <p>The only difference is the size. The Forever Framette is just a smaller, compact version of the Forever Frame. It has all the same features, functions and colors in a smaller size. It takes 1 total cup of sand to fill to the Keeper Plate.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">Can I fill the frame to the top with sand and place the photo in front of the sand?</h3>
                <div class="block-content">
                    <p>YES. The removable glass photo pane allows the photo to be in front of the sand or behind. It is your choice.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">If I want to fill the frame to the top with unity sand, how much will I need?</h3>
                <div class="block-content">
                    <p>Forever Frame: You will need 7 cups of sand. That translates to around 7 1-lb. bags.</p>
                    <p>Forever Framette: You will need 3 ½ cups of sand. That translates to around 4 1-lb. bags.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">What size picture will my frame hold?</h3>
                <div class="block-content">
                    <p>Photo squares are included with your frame.</p>
                    <p>Forever Frame: Any size photo up to an 8 x 10 can be used, as well as a few small photos at once, however we recommend a 5 x 7 photo for portrait orientation and a 4 x 6 photo for landscape orientation.</p>
                    <p>Forever Framette: Any size photo up to a 5 x 7 can be used, as well as a few small photos at once, however we recommend a 4 x 6 photo for portrait orientation and a 3 x 5 photo for landscape orientation.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">How do I mount the photo in The Forever Frame&trade;?</h3>
                <div class="block-content">
                    <p>Clear adhesive Photo Mounting Corners (picture squares) are included in the frame. The rear pane of glass slides out. Place a photo square on each corner of the photo you will use. Position the photo taking into account that sand will fill the bottom 1/3 of the frame. Press the corners to adhere the photo to the glass.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">How much does The Forever Frame&trade; weigh?</h3>
                <div class="block-content">
                    <p>Without sand the frame weighs 5 lbs. With 2 and 1/4 cups of sand the frame weighs 6.5 lbs.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">How much does The Forever Framette&trade; weigh?</h3>
                <div class="block-content">
                    <p>Without sand the frame weighs 3.5 lbs. With 1 cup of sand the frame weighs 4.5 lbs.</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">What are the dimensions of The Forever Frame&trade;?</h3>
                <div class="block-content">
                    <p>The outer dimension of the frame is 11.25" x 9" x 3".</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">What are the dimensions of The Forever Framette&trade;?</h3>
                <div class="block-content">
                    <p>The outer dimension of the framette is 9" x 6" x 3".</p>
                </div>
            </div>
            <div class="collapsible">
                <h3 class="block-title">What is the cost of shipping The Forever Frame&trade;?</h3>
                <div class="block-content">
                    <p>We use FedEx and charge shipping according to the weight and destination of the order (which depends on the inclusion of sand or vessels).  You can estimate the cost of your shipping by going to the Shopping cart (before checkout), add your desired products to the cart and use the Estimate Shipping tool. If you have certain questions <a href="mailto:elaine@theforeverframe.com" target="_blank">elaine@theforeverframe.com</a> for specific shipping prices.</p>
                </div>
            </div>
        </article>
    </section>
</div> <!-- end grid12-9 -->

<div class="grid12-3">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_top')->toHtml();
    ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_bottom')->toHtml();
    ?>
</div>