<div class="compare grid-container">
    <div class="feature grid12-6">
        <img class="icon" src="<?php echo Mage::getBaseUrl('media') . "wysiwyg/infortis/ultimo/icons/info.png"; ?>" alt="Compare the competition" />
        <h6 class="above-heading">See for yourself</h6>
        <h3>Compare the Competition!</h3>

        <ul class="bullet">
            <li>The perfect sand shadow box</li>
            <li>Prevents sand from mixing</li>
            <li>Perfect for travel</li>
            <li>Exchange photos any time</li>
            <li>Extremely versatile</li>
            <li><a href="http://www.favourlicious.ca" target="_blank">Canadian customers</a> save shipping and customs charges!</li>
        </ul>
        <script src='//www.weddingwire.com/assets/vendor/widgets/ww-rated-2013.js' type='application/javascript'></script><div id='ww-widget-wwrated-2013'><a class="ww-top" href="http://www.weddingwire.com" target="_blank" title="Weddings, Wedding, Wedding Venues"></a><a class="ww-bottom" href="http://www.weddingwire.com/reviews/the-forever-frame-gilbert/cfa97f7c8fd3cdc3.html" target="_blank"         title="The Forever Frame Reviews, Phoenix  Favors &amp; Gifts"></a></div><script>  WeddingWire.ensureInit(function() {WeddingWire.createWWRated2013({"vendorId":"cfa97f7c8fd3cdc3" }); });</script>
    </div>
    <div class="grid12-6">
        <div class="video-container">
            <iframe width="556" height="313" src="https://www.youtube.com/embed/hfTD3vXCpcs" frameborder="0" allowfullscreen></iframe>
        </div> <!-- end video-container -->
    </div>
</div> <!-- end grid-container -->
<br/>
<br/>
<br/>

<!--<div class="grid12-4">

        <div class="feature feature-icon-hover indent indent-size-xl">
        <span class="ic ic-2x ic-paint ib ib-size-xl"></span>
        <h6 class="above-heading">Customizable design</h6>
        <h3>Unlimited Colors</h3>
        <p>You have never seen so many options! Change colors of dozens of elements, apply textures, upload background images...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>

<div class="grid12-4">

    <div class="feature feature-icon-hover indent indent-size-xl">
        <span class="ic ic-2x ic-smartphones ib ib-size-xl"></span>
        <h6 class="above-heading">12-column grid</h6>
        <h3>Responsive Layout</h3>
        <p>Ultimo can be displayed on any screen. It is based on fluid grid system. If screen is resized, layout will be automatically adjusted...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div>

<div class="grid12-4">

    <div class="feature feature-icon-hover indent indent-size-xl">
        <span class="ic ic-2x ic-menu ib ib-size-xl"></span>
        <h6 class="above-heading">Customizable drop-down menu</h6>
        <h3>Mega Menu</h3>
        <p>Two styles: wide mega menu or classic drop-down menu. You can add any custom content (images, text, HTML) to any category in the catalog...</p>
        <a href="{{store url='ultimo-responsive-magento-theme'}}" class="go">See all features</a>
    </div>

</div> -->

<!-- <div class="grid-container page-banners">
    <div class="grid12-4 no-left-gutter banner">

        <img src="{{media url="wysiwyg/infortis/ultimo/custom/banners/2a.png"}}" alt="Sample banner" />
        <br/><br/>

    </div>
    <div class="grid12-4">

        <div class="feature feature-icon-hover indent first">
            <span class="ic ic-char ib" style="background-color: #ddd;">1</span>
            <h4>Responsive Layout</h4>
            <p>Ultimo can be displayed on any screen. <span class="hide-below-1280">It is based on fluid grid system lorem ipsum dolor sit.</span> <span class="hide-below-960">If screen is resized, layout will be automat...</span></p>
        </div>
        <div class="feature feature-icon-hover indent">
            <span class="ic ic-char ib" style="background-color: #ddd;">2</span>
            <h4>Responsive Layout</h4>
            <p>Ultimo can be displayed on any screen. <span class="hide-below-1280">It is based on fluid grid system lorem ipsum dolor sit.</span> <span class="hide-below-960">If screen is resized, layout will be automat...</span></p>
        </div>
        <div class="feature feature-icon-hover indent last">
            <span class="ic ic-char ib" style="background-color: #ddd;">3</span>
            <h4>Responsive Layout</h4>
            <p>Ultimo can be displayed on any screen. <span class="hide-below-1280">It is based on fluid grid system lorem ipsum dolor sit.</span> <span class="hide-below-960">If screen is resized, layout will be automat...</span></p>
        </div>

    </div>
    <div class="grid12-4 no-right-gutter hide-below-768">

        <div class="page-banners grid-container-spaced">
            <div class="grid12-12 no-gutter banner fade-on-hover">
                <a href="#">
                    <img src="{{media url="wysiwyg/infortis/ultimo/custom/banners/3a.jpg"}}" alt="Sample banner" />
                </a>
            </div>
            <div class="grid12-6 no-left-gutter banner fade-on-hover">
                <a href="#">
                    <img src="{{media url="wysiwyg/infortis/ultimo/custom/banners/3b.jpg"}}" alt="Sample banner" />
                </a>
            </div>
            <div class="grid12-6 no-right-gutter banner fade-on-hover">
                <a href="#">
                    <img src="{{media url="wysiwyg/infortis/ultimo/custom/banners/3c.jpg"}}" alt="Sample banner" />
                </a>
            </div>
        </div>

    </div>
</div> -->

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new_products')->toHtml(); ?>

<!-- <span class="section-title">Sample Custom Banners</span>
<br />
<div class="nested-container"> -->

    <!-- First banner has a link which adds a product to the cart (link was copied from product's button "Add to cart") -->
    <!-- <div class="page-banners grid-container">
        <div class="grid12-3 banner fade-on-hover hide-below-768">
            <a href="{{store direct_url='checkout/cart/add/uenc/aHR0cDovL2xvY2FsaG9zdC5jb20vbTE3MDItMDF1bHRpbW8vZGVmYXVsdC8,/product/30/'}}" title="Click to add sample product to your cart">
                <img class="fade-on-hover" src="{{media url="wysiwyg/infortis/ultimo/custom/banners/1a.png"}}" alt="Add product to cart" />
            </a>
        </div>
        <div class="grid12-3 banner fade-on-hover hide-below-768">
            <a href="{{store direct_url='checkout/cart/'}}" title="Click to go to cart page">
                <img class="fade-on-hover" src="{{media url="wysiwyg/infortis/ultimo/custom/banners/1b.png"}}" alt="Go to Magento cart page" />
            </a>
        </div>
        <div class="grid12-6 banner">
                <img class="fade-on-hover" src="{{media url="wysiwyg/infortis/ultimo/custom/banners/1c.png"}}" alt="Magento discount code" title="Use discount code/coupon on cart page" />
        </div>
    </div>

</div> -->