<div class="grid12-9">
    <section>
        <h1>Check out our Instructional Video!</h1>
        <article>
            <div class="video-container" style="margin-bottom:30px;">
                <iframe width="853" height="480" src="https://www.youtube.com/embed/iXDsE9IoMk8" frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="grid-container-spaced steps">
                <div class="grid12-12 collapsible mobile-collapsible active">
                    <h3 class="block-title">Step 1</h3>
                    <div class="block-content">
                        <p><img src="<?php echo $this->getSkinUrl('images/instructions_step1.jpg') ?>">
                            Affix a photo to rear glass using included photo mounts. Exchange picture any time without disturbing the sand.</p>
                    </div>
                </div>
                <div class="grid12-12 collapsible mobile-collapsible">
                    <h3 class="block-title">Step 2</h3>
                    <div class="block-content">
                        <p><img src="<?php echo $this->getSkinUrl('images/instructions_step2.jpg') ?>">
                            Pour sand by alternating each pour to achieve an artful pattern.</p>
                    </div>
                </div>
                <div class="grid12-12 collapsible mobile-collapsible">
                    <h3 class="block-title">Step 3</h3>
                    <div class="block-content">
                        <p><img src="<?php echo $this->getSkinUrl('images/instructions_step3.jpg') ?>">
                            Insert included Keeper Plate to lock sand in place & preserve your design.</p>
                    </div>
                </div>
                <div class="grid12-12 collapsible mobile-collapsible">
                    <h3 class="block-title">Step 4</h3>
                    <div class="block-content">
                        <p><img src="<?php echo $this->getSkinUrl('images/instructions_step4.jpg') ?>">
                            Slide the lid into place.</p>
                    </div>
                </div>
            </div> <!-- end grid-container-spaced -->

            <div class="grid12-12">
                <h2>Please Read These Instructions Completely</h2>
                <h3>Pre-Ceremony</h3>
                <ol>
                    <li>Select sand colors and pouring containers.</li>
                    <li>Measure each color of sand into a container according to the chart below.</li>
                    <li>Set up The Forever Frame at the ceremony so it’s visible to your guests during the ceremony.</li>
                    <li>Remove the Keeper Plate™ and lid from frame and place them out of site behind the frame. DO NOT LOSE THE KEEPER PLATE.</li>
                    <li>Delegate someone you trust to take care of your Forever Frame after the ceremony, i.e., Maid of Honor, a bride’s maid, Best Man, a groomsman or family member. Make sure they know that the Keeper Plate™ should NOT be thrown away or lost.</li>
                </ol>
                <h4>Forever Frame</h4>
                <div class="grid12-6">
                    <h5>Filling to the keeper plate</h5>
                    <table class="frameFill">
                        <tr>
                            <th># Colors Used</th>
                            <th>Cups (2 1/4 total)</th>
                            <th>Ounces (18 total)</th>
                            <th>Grams (853 total)</th>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>1 1/8</td>
                            <td>9</td>
                            <td>427</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>3/4</td>
                            <td>6</td>
                            <td>284</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>4/7</td>
                            <td>4.5</td>
                            <td>213</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>4/9</td>
                            <td>3.6</td>
                            <td>171</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>3/8</td>
                            <td>3</td>
                            <td>142</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>1/3</td>
                            <td>2.6</td>
                            <td>122</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>3 5/9</td>
                            <td>2.3</td>
                            <td>427</td>
                        </tr>
                    </table>
                </div> <!-- end grid12-6 -->
                <div class="grid12-6">
                    <h5>Filling to the top</h5>
                    <table class="frameFill">
                        <tr>
                            <th># Colors Used</th>
                            <th>Cups (7 total)</th>
                            <th>Ounces (56 total)</th>
                            <th>Grams (2653 total)</th>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>3 1/2</td>
                            <td>28</td>
                            <td>1327</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>2 1/3</td>
                            <td>18.7</td>
                            <td>884</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>1 3/4</td>
                            <td>14</td>
                            <td>663</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>1 2/5</td>
                            <td>11.2</td>
                            <td>531</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>1 1/6</td>
                            <td>9.3</td>
                            <td>442</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>1</td>
                            <td>8</td>
                            <td>379</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>1 1/7</td>
                            <td>7</td>
                            <td>332</td>
                        </tr>
                    </table>
                </div> <!-- end grid12-6 -->
                <h4>Forever Framette</h4>
                <div class="grid12-6">
                    <h5>Filling to the keeper plate</h5>
                    <table class="frameFill">
                        <tr>
                            <th># Colors Used</th>
                            <th>Cups (1 total)</th>
                            <th>Ounces 18 total)</th>
                            <th>Grams (390 total)</th>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>1/2</td>
                            <td>4</td>
                            <td>195</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>1/3</td>
                            <td>0.375</td>
                            <td>170</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>1/4</td>
                            <td>2</td>
                            <td>128</td>
                        </tr>
                    </table>
                </div> <!-- end grid12-6 -->
                <div class="grid12-6">
                    <h5>Filling to the top</h5>
                    <table class="frameFill">
                        <tr>
                            <th># Colors Used</th>
                            <th>Cups (3 1/2 total)</th>
                            <th>Ounces (28 total)</th>
                            <th>Grams (1326 total)</th>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>1 3/4</td>
                            <td>14</td>
                            <td>663</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>1 1/6</td>
                            <td>9.33</td>
                            <td>442</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>7/8</td>
                            <td>7</td>
                            <td>332</td>
                        </tr>
                    </table>
                </div> <!-- end grid12-6 -->
                <p>NOTE:  You MUST use the correct amount of sand to ensure the Keeper Plate™ fits. It is better to under-fill than over-fill. You can always add more after the ceremony.</p>

                <h3>During Ceremony</h3>
                <ol>
                    <li>Take turns slowly pouring each different color of sand into the sealed chamber.</li>
                    <li>Have the officiant or special someone read a prepared dialogue while pouring to make it more special.</li>
                </ol>

                <h3>Post Ceremony</h3>
                <ol>
                    <li>Your chosen Forever Frame steward will need to follow these simple steps:</li>
                    <ul>
                        <li>Gently move The Forever Frame side to side to level out the sand.</li>
                        <li>Insert the Keeper Plate.</li>
                        <li>Slide on the Lid.</li>
                    </ul>
                    <li>Add keepsakes from the ceremony or reception to the frame (champagne cork, match book, flower petals, etc.)</li>
                </ol>

                <h3>Travel Home</h3>
                <ol>
                    <li>CARRY the frame in an UPRIGHT position at all times as a carry-on in a back pack or separate bag. Do NOT store it lying down under the seat or in the overhead.</li>
                </ol>
                <p>NOTE: Although the Keeper Plate™ will prevent the sand from moving freely, it will not hold up to jarring, shaking or banging around.</p>
                <p>When you receive your wedding photos, you can exchange the photo used at the ceremony with a professional photo. </p>
            </div>
        </article>
    </section>
</div> <!-- end grid12-9 -->

<div class="grid12-3">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_top')->toHtml();
    ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_bottom')->toHtml();
    ?>
</div>

<!--                <div class="grid12-12 collapsible mobile-collapsible">-->
<!--                    <h3 class="block-title">Step 5</h3>-->
<!--                    <div class="block-content">-->
<!--                        <p>Display your unique frame as a reminder of the special occasion.</p>-->
<!--                        <img src="--><?php //echo $this->getSkinUrl('images/instructions_step5.jpg') ?><!--">-->
<!--                    </div>-->
<!--                </div>-->
<!--<img src=--><?php //echo $this->getSkinUrl('images/about-us2.jpg') ?><!-- title="Sand Colors: White and Ocean Blue" alt="The Forever Frame" />-->

