<div class="grid12-9">
    <section>
        <h1>Helpful Hints for a Successful Unity Sand Ceremony</h1>
        <article>
            <div class="collapsible">
                <h2 class="block-title">Use an officiant that is experienced and skilled in Unity Sand Ceremonies</h2>
                <div class="block-content">
                    <p>Minister Larry James voted "Best Officiant" in 2007 and 2008 and the Reverand Giovanni voted Bride's Choice 2010 have been conducting unity sand ceremonies for over a decade. Visit <a href="http://www.celebrateintimateweddings.com" target="_blank">Celebrate Intimate Weddings</a> for Minister Larry James. Visit <a href="http://www.revgiovanni.com/RevGio/Welcome.html" target="_blank">Reverand Giovanni</a> for the Reverand Giovanni and get lots of ideas and information regarding incorporating a sand ceremony into your wedding!</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Take turns pouring each color</h2>
                <div class="block-content">
                    <p>Instead of pouring all at once together, take turns pouring each separate color a little at a time to get a more marbleized design.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Personalize the pouring vases for children</h2>
                <div class="block-content">
                    <p>If this is a second marriage or even a first marriage where the children will join in the unity sand ceremony, consider having the pouring vase engraved with the children's names to help them feel even more a part of the event and retain a special keepsake from the big day.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">For Destination Weddings, transport the frame home in a back pack or bag as a carry on in an upright position</h2>
                <div class="block-content">
                    <p>Although the Keeper Plate will prevent the sand from mixing when the frame is moved, it will not withstand a baggage handler's abuse.  We strongly recommend that you transport the frame home as a carry on in an upright position to further ensure the sand remains as you poured it.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Choose a location easily visible to your guests.</h2>
                <div class="block-content">
                    <p>Make sure you have an ideal spot picked out to place your Forever Frame.  A small table, which allows you to stand to both sides, is ideal.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Be creative with the sand ceremony display and setup.</h2>
                <div class="block-content">
                    <p>You can place The Forever Frame&trade; and unity sand on the table prior to the unity ceremony starting, or have the mothers, flower girls or special guests place the <a href="http://www.foreverframe.com/corked-tapered-vessell.html">sand vessels</a> by The Forever Frame as part of the entrance ceremony.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Include your parents, children or friends in the unity sand ceremony</h2>
                <div class="block-content">
                    <p>Additional colors of sand can be used to symbolize a blending of families, your children or your guests.</p>
                    <p>Have your chosen loved one join you in the ceremony to pour their color.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Use an accent color to symbolize your wedding location.</h2>
                <div class="block-content">
                    <p>If using more than 2 colors, don't be afraid to pour an accent sand color into the frame prior to the ceremony if it fits your vision better.</p>
                    <p>For example, a Sedona Arizona wedding may include a red or terracotta color below your design and when the ceremony is complete, the same color can be poured on top to complete the look.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Humidity can sometimes be an issue for a unity sand ceremony.</h2>
                <div class="block-content">
                    <p>If you are using The Forever Frame&trade; bottles, ensure the corks are secured tightly to prevent moisture from mixing with the sand. If using a vessel with no top, have your Maid of Honor or Best Man take a moment to make sure the sand has not clumped prior to the ceremony.</p>
                </div>
            </div>
            <div class="collapsible">
                <h2 class="block-title">Preserve your unity sand design in The Forever Frame&trade; so it won't move.</h2>
                <div class="block-content">
                    <p>To keep the sand design the way it is the day of your wedding you will want to delegate someone prior to the ceremony to take care of your Forever Frame after the ceremony, i.e., Maid of Honor, a bride's maid, Best Man, a groomsman or family member.</p>
                    <p>He/she will need to follow these simple steps:</p>
                    <ol id="tips">
                        <li>Gently move The Forever Frame&trade; side to side to level out the sand.</li>
                        <li>Place the keeper plate&trade; in the sand chamber</li>
                    </ol>
                </div>
            </div>
        </article>
    </section>
</div> <!-- end grid12-9 -->

<div class="grid12-3">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_top')->toHtml();
    ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_right_bottom')->toHtml();
    ?>
</div>