<div class="grid12-9">
    <section class="left-col">
        <h1>Our Preferred Vendors</h1>
        <article>

            <ul class="vendors">
                <h3>Salons</h3>

                <li>Contact: Cathy Walter</li>
                <li>Website: <a href="http://www.BarlonSalon.com">Barlon Salon ~ The Salon of Diversion</a></li>
            </ul>

            <ul class="vendors">
                <h3>Officiants</h3>

                <li>Contact: Larry James</li>
                <li>Website: <a href="http://www.celebrateintimateweddings.com">Celebrate Intimate Weddings</a></li>

                <li>Contact: Reverend Giovanni</li>
                <li>Website: <a href="http://www.revgiovanni.com/RevGio/Welcome.html">Reverend Giovanni Weddings</a></li>
            </ul>

            <ul class="vendors">
                <h3>Venues</h3>

                <li>Newport Beach Marriott Hotel and Spa</li>
                <li>Website: <a href="https://www.marriott.com/hotels/event-planning/wedding-planning/laxnb-newport-beach-marriott-hotel-and-spa/">Newport Beach Weddings - Marriot Hotel & Spa</a></li>
            </ul>

            <ul class="vendors">
                <h3>Videographer</h3>

                <li>Contact: Les Bradley</li>
                <li>Website: <a href="http://www.morrfilm.com">Morr Film and Video</a></li>
            </ul>

            <ul class="vendors">
                <h3>Wedding Decor Suppliers</h3>

                <li>Sandsational Sparkle</li>
                <li>Website: <a href="http://www.sandsationalsparkle.com/">Sandsational Sparkle</a></li>

                <li>Thee Wedding & Event Warehouse</li>
                <li>Website: <a href="http://www.theeweddingwarehouse.com/">Thee Wedding & Event Warehouse</a></li>
            </ul>

            <ul class="vendors">
                <h3>Wedding Planners</h3>

                <li>Dreamers Event Planners</li>
                <li>Website: <a href="http://www.dreamerseventplanners.com/">Dreamers Event Planners</a></li>
            </ul>
        </article>
    </section>
